
general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

animations {
    enabled = true

    bezier = linear, 0.25, 0.1, 0.25, 1.0

    animation = fadeIn, 1, 10, linear
    animation = fadeOut, 1, 10, linear
    animation = inputFieldDots, 1, 1, linear
}

input-field {
    size = 400, 60
    position = 0, -37%

    rounding = 0
    dots_size = 0.5
    dots_text_format = *

    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    check_color = rgba(0, 0, 0, 0)
    fail_color  = rgba(0, 0, 0, 0)

    font_family = CaskaydiaCove Nerd Font
    font_color  = rgba(255, 255, 255, 1)

    placeholder_text =
    fail_text = <b>Wrong password!</b>

    outline_thickness = 0
}

label {
    text = $TIME12
    font_family = Maple Mono
    font_size = 78

    position = 0, 25%
    halign = center
    valign = center
}

background {
    monitor = eDP-1
    path = ~/ikigai/currentwall
    blur_size = 4
}
